# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217a85d9bd8c8eab764599f071818d60fa7deaf14e607da6da6ee00d37ef5a2444f43b62993c218d7896672a571fbc279b23fe04d42c2fc4cc32769b5491f050

test:
  secret_key_base: 96caa1232e920df760745ce2996d69ddf3caeab64239f23dcd388af284d865c8334808427dad2377b97fce7eec613da184f5086b57dcd931060c67eccad2c8ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
